import '../../css/Random.css'
const Math4 = () => {
    return (
        <div>
            <h1>Chips on an Infinite Chessboard</h1>
            <h3>We study an infinite chessboard where each square may have a pile of chips. A tremor may randomly topple any square with a pile of four or more chips, removing four chips from that pile and adding one to each of its neighbors in a cardinal direction. In this paper, we focus on stable states, chip configurations where no more tremors can occur. We prove that any starting configuration with a finite number of chips has a reachable, unique stable state. We explore a specific starting configuration, where all chips on the board start in the same square, and provide a bound on the number of steps it will take to reach the stable state in terms of the initial number of chips. We then study some specific cases with an infinite number of chips on the infinite chessboard generated by repeating a small pattern, or kernel. We show a kernel whose board does not reach stability, and we show that all boards generated by a 2 by 2 kernel with under 8 chips will reach stability. Our full paper is{' '}
                <a href="https://drive.google.com/file/d/1KcjK2V6jNfh_Vslet0rQQZC1AGHj8PFP/view?usp=sharing">
                     here.
                </a>
            </h3>
            <div className="image-container">
                <div className="image-item">
                    <h3>Initial configuration.</h3>
                    <img src="https://ik.imagekit.io/j91ks0fc6/lattice1.png?updatedAt=1732072232068" />
                </div>
                <div className="image-item">
                    <h3>Configuration resulting from a redistribution of the red vertex, which donates one chip to each green vertex</h3>
                    <img src="https://ik.imagekit.io/j91ks0fc6/lattice2.png?updatedAt=1732072260869" />
                </div>
            </div>
        </div>
    )
}
export default Math4